resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 4
        slow-call-duration-threshold: 3s
        slow-call-rate-threshold: 50
    instances:
      products:
        base-config: default
  timelimiter:
    configs:
      default:
        timeout-duration: 3s
    instances:
      products:
        base-config: default

spring:
  cloud:
    gateway:
      routes:
      - id: msvc-products
        uri: lb://msvc-products
        predicates:
        - Path=/api/products/**
        # - Header=Authorization, Bearer \d+
        # - Method=GET, POST
        # - Query=color
        # - Cookie=color, azul
        # - Header=Content-Type, application/json
        filters:
        - StripPrefix=2
        - name: SampleCookie
          args:
            name: user
            value: Cesar
            message: Hola soy una cookie personalizada para productos
        #- CircuitBreaker=products
        - name: CircuitBreaker
          args:
            name: products
            statusCodes: 500
            fallbackUri: forward:/api/items/api/v1/items/5

      - id: msvc-items
        uri: lb://msvc-items
        predicates:
        - Path=/api/items/**
        filters:
        - StripPrefix=2
        - AddRequestHeader=token-request, aaaaaaa
        - AddResponseHeader=token-response, bbbbbb
        - AddRequestParameter=name, Octavio
        #- SetResponseHeader=Content-Type, text/plain

      - id: msvc-users
        uri: lb://msvc-users
        predicates:
        - Path=/api/users/**
        filters:
        - StripPrefix=2
